export const PROBLEM_STEPS_DATA = [
            // ✅ 問題解決型步驟 (問題解決型)
            { id: 1, name: "主題選定", 
              quiz: [{ question: "問題解決型的『主題選定』，下列何者為錯誤的敘述？", 
                     options: ["主題必須能清楚定義量化指標作為後續目標設定依據。", 
                               "主題一覽表應該明確定義出評分依據。", 
                               "應描述主題的重要性、迫切性。", 
                                 "主題選定不需要過多說明候選主題的由來，只需撰寫評分後的結果。"],
                     correctAnswerIndex: 3, step: "主題選定", 
                     feedback_correct: "🎯 完美命中！看來實力非凡!", 
                     feedback_incorrect: "🤔 答錯囉！應該要說明候選主題的由來以及評分後的結果喔！" }] },
            { id: 2, name: "現狀把握", 
             quiz: [{ question: "問題解決型的『現狀把握』，下列何者為錯誤的敘述？", 
                     options: ["收集過去相關數據找出問題點。", 
                               "僅根據過往經驗或個人判斷現況問題。", 
                               "使用層別法分析過去數據，找出現況問題。", 
                               "使用柏拉圖搭配80/20法則找出問題。"], 
                     
                     correctAnswerIndex: 1, step: "現狀把握", 
                     feedback_correct: "✅ 答對了  觀念非常正確！。", 
                     feedback_incorrect: "🔍 不應單憑過去經驗判斷問題，應以客觀數據為依據。" }] },
            { id: 3, name: "目標設定", 
             quiz: [{ question: "下列哪一項不是設定目標值的依據？", 
                     options: ["團隊推估。", "S.M.A.R.T.原則。", "文獻。", "內外部標竿機構。"], 
                     correctAnswerIndex: 0, step: "目標設定", 
                     feedback_correct: "🌟 太棒了~恭喜答對。", 
                     feedback_incorrect: "❌設定的依據必須是有所本的，不能自己喊一個數值" }] },
            
             { id: 4, name: "原因分析", 
             quiz: [{ question: "在『原因分析』階段，哪個手法不適合用於原因分析？", 
                     options: ["柏拉圖。", "關聯圖。", "魚骨圖 (特性要因圖)。", "系統圖。"], 
                     correctAnswerIndex: 0, step: "原因分析", 
                     feedback_correct: "💡 真聰明！概念非常正確，沒有被誤導。", 
                     feedback_incorrect: "😵‍ 柏拉圖通常是用在現況把握找尋問題並不適用於深入進行原因分析" }] },
            { id: 5, name: "對策擬定", 
             quiz: [{ question: "下列哪一項敘述關於『對策擬定』是錯誤的？", 
                     options: ["每個真因至少要有一個對策以上。", 
                          "相同/類似的對策可以使用對策群組。", 
                               "對策擬定可以使用矩陣圖來評估各對策是否可以採用與執行。", 
                               "對策擬定一定要使用經濟性、效益性、可行性來評分。"], 
                     correctAnswerIndex: 3, step: 
                    "對策擬定", 
                     feedback_correct: "👍 沒錯！恭喜你答對啦~題目是不是很變態，只有融會貫通才會知道正確答案喔。", 
                     feedback_incorrect: "🚧 NO!NO!評分的面向可以自己設定，不一定是經濟性、效益性、可行性喔~" }] },
            { id: 6, name: "對策實施", 
             quiz: [{ question: "關於『對策實施的描述』，下列何者為錯誤？", 
                      options: ["對策是為了消除真因，因此 Check 應該要評估是否有效消除真因。", 
                               "在對策推動過程中若遇到障礙，應檢討原因並適時調整計畫。", 
                               "若為了瞭解各對策是否有效，因此可以分階段實施對策。", 
                        "為確保對策能順利執行，應在未確認真因前就先全面推動所有改善措施，以免延誤時程。"], 
                     correctAnswerIndex: 3, step: "對策實施", 
                     feedback_correct: "📅 概念非常正確！。", 
                     feedback_incorrect: "❌ 答錯囉！未確認真因前就全面推動對策，會造成改善方向錯誤！" }] },
            { id: 7, name: "效果確認", 
                     // *** 這裡是上次修改過的題型 ***
                     quiz: [{ question: "請問下面哪些內容是『可以寫在效果確認』？",
                     options: ["目標是否確實達成並以數據呈現。", "紙張使用量減少。", 
                               "團隊士氣與改善概念提升。", "以上皆是。"], 
                     correctAnswerIndex: 3, step: "效果確認", 
                     feedback_correct: "💰 專業！以上都可以寫在最後總效果確認裡喔。", 
                     feedback_incorrect: "👀 答錯了！效果確認還包含『有形』(數據)和『無形』(軟性)效果以及附加效益。" }] },
            { id: 8, name: "標準化與維持", 
             quiz: [{ question: "關於『標準化與維持』，下列敘述何者正確？", 
                      options: ["標準化僅指把改善流程寫成SOP，不需進行教育訓練或宣導", 
                               "目的是確保改善成果能長期維持。", 
                               "成果達到一次就可結束，無需定期追蹤或持續改善。", 
                        "標準化只需將改善流程寫成SOP，即可長期維持成果。"], 
                     correctAnswerIndex: 1, step: "標準化與維持", 
                     feedback_correct: "👑 沒錯！標準化後仍需維持與追蹤，以確保長期效果。", 
                     feedback_incorrect: "🔒 標準化不是結束，而是『維持』！因此需要教育訓練，確保流程落實執行。" }] },
            { id: 9, name: "檢討與下一步", 
                       quiz: [{ question: "下列哪些內容屬於『檢討與改進』階段可以撰寫的方向？", 
                     options: ["可針對各步驟提出優化建議。", 
                               "應找出殘留問題，包含最初沒改善到的部分，以及改善後可能出現的新問題。", 
                        "殘留問題都可以納入下次改善的主題之一。", 
                               "以上皆是。"], 
                     correctAnswerIndex: 3, step: "檢討與改進", 
                     feedback_correct: "🚀 正確！恭喜你已經做完所有題目囉~", 
                       feedback_incorrect: "💡 答案是以上皆是喔~" }] }
        ];

export const SOLUTION_STEPS_DATA = [
            // ✅ 課達型步驟 (課題達成型)
            { id: 1, name: "主題選定", quiz: [{ question: "QCC 選擇『課題達成型』課題時，依據的主要方向是什麼？", options: ["從現場問題中挑選影響較大的項目。", "根據公司方針或部門中長期目標來選擇。", "由最高管理層直接指定。", "成員個人感興趣且容易執行的項目。"], correctAnswerIndex: 1, step: "選定課題", feedback_correct: "🎯 完美命中！課題達成型更注重與組織策略目標的連結。", feedback_incorrect: "🤔 答錯囉！課題達成型通常是自上而下的，以目標為導向，而非解決現有問題。" }] },
            { id: 2, name: "現狀分析", quiz: [{ question: "『現狀分析』的關鍵是找出什麼？", options: ["找出所有可能的對策。", "掌握現況與公司目標之間的『差距』。", "使用魚骨圖找出根本原因。", "制定詳細的實施計畫。"], correctAnswerIndex: 1, step: "現狀分析", feedback_correct: "✅ 正確！課題達成型分析現狀是為了量化『目標與現況之間的落差』。", feedback_incorrect: "🔍 接近了！課題達成型分析現狀的重點是找出與目標之間的差距，以便擬定策略。" }] },
            { id: 3, name: "目標設定", quiz: [{ question: "設定課題達成型目標時，除了數值外，還需具備哪項重要資訊？", options: ["對策的詳細實施步驟。", "達成目標所需的資源投入。", "明確的『達成時間點』或期限。", "所有成員的個人期望。"], correctAnswerIndex: 2, step: "目標設定", feedback_correct: "🌟 就是這個！課題達成型目標必須具備時間性，否則難以追蹤達成率。", feedback_incorrect: "❌ 目標需要具備時間性，才能納入計畫管理中，確保進度！" }] },
            { id: 4, name: "要因分析", quiz: [{ question: "在『要因分析』中，主要目的是找出哪些因素？", options: ["過去造成品質問題的根本原因。", "影響『目標達成』的主要障礙或變動因素。", "競爭對手的產品優勢。", "所有可能的對策與方案。"], correctAnswerIndex: 1, step: "要因分析", feedback_correct: "💡 聰明！課題達成型關注的是『目標達成』的障礙，而不是現有問題的原因。", feedback_incorrect: "😵‍ 喔喔！要因分析的重點是找出達成目標路徑上的『阻力』！" }] },
            { id: 5, name: "對策擬定", quiz: [{ question: "制定課題達成型對策時，主要目的是確保計畫能達到什麼要求？", options: ["確保對策能夠一次性徹底解決問題。", "確保對策能夠彌補現況與目標之間的『差距』。", "確保對策費用最低。", "確保對策最具創新性。"], correctAnswerIndex: 1, step: "對策擬定", feedback_correct: "👍 沒錯！對策是彌補差距的手段，必須有策略性。", 
                    feedback_incorrect: "🚧 小心！課題達成型對策的戰略目標是彌補分析階段找出的目標差距。" }] },
            { id: 6, name: "實施計畫", quiz: [{ question: "在『實施計畫』階段，為了確保資源有效利用，最關鍵的動作是？", options: ["進行全員教育訓練。", "明確責任人、時程、預算與追蹤機制。", "進行對策的初步試驗。", "撰寫詳細的總結報告。"], correctAnswerIndex: 1, step: "實施計畫", feedback_correct: "📅 正確！明確的權責和資源分配，是實施計畫順利推進的保障。", feedback_incorrect: "❌ 實施計畫的重點是資源與進度追蹤，必須明確分配權責！" }] },
            { id: 7, name: "效果確認", quiz: [{ question: "課題達成型的『效果確認』主要關注什麼？", options: ["是否帶來額外的士氣提升。", "是否達到預先設定的『目標達成率』。", "是否有形與無形效果。", "對策實施的難易度。"], correctAnswerIndex: 1, step: "效果確認", feedback_correct: "💰 專業！課題達成型最直接的評估就是達成目標的程度。", feedback_incorrect: "👀 答錯了！課題達成型最核心的指標就是目標達成率，這是檢視課題是否完成的依據。" }] },
            { id: 8, name: "標準化與維持", quiz: [{ question: "課題達成型『標準化與維持』的主要目的是什麼？", options: 
                        ["將成功的『新方法』或『新標準』制度化。", "計算成員的個人績效獎金。", "找出下一輪的改善課題。", "舉行慶祝活動。"], correctAnswerIndex: 0, step: "標準化與維持", feedback_correct: "👑 沒錯！成功達成目標後，需將新的、更好的做法固化為標準。", feedback_incorrect: "🔒 標準化是將成功經驗轉為常規作業，防止退步！" }] },
            { id: 9, name: "檢討與展望", quiz: [{ question: "課題達成型 QCC 的『檢討與展望』階段的核心輸出是什麼？", options: ["向管理層申請資金。", "總結活動，並提出『未來持續改善或擴大的課題』。", "僅記錄活動過程，不做任何結論。", "對所有成員進行績效考核。"], correctAnswerIndex: 1, step: "檢討與展望", feedback_correct: "🚀 正確！總結活動和提出未來展望，才能讓 QCC 形成持續改善的循環。", feedback_incorrect: "💡 總結活動和提出未來展望，才能讓 QCC 形成持續改善的循環！" }] }
        ];
